; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_flap_sound

@sfx_ntsc_flap_sound:
	.byte $8a,$06,$02,$89,$31,$01,$89,$32,$01,$89,$33,$01,$89,$34,$01,$89
	.byte $35,$01,$89,$37,$01,$89,$3a,$01,$89,$3d,$01,$89,$3f,$01,$89,$3c
	.byte $01,$89,$39,$01,$89,$35,$01,$89,$32,$01,$00

.export sounds
